import Head from 'next/head'
 
import styled from 'styled-components'
import Contact from '../sections/Contact'
import CourseList from '../sections/CourseList'
import Hero from '../sections/Hero'
import PostList from '../sections/PostList'
import Questions from '../sections/Questions'


export const Title = styled.h1`
  font-size:50px;
`


 function Home({className}) {
  return (
    <>
      <Head>
        <title>BIMCapacitacion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Questions/>
      <CourseList/>
      <PostList/>
      <Contact/>
    
    </>
  )
}

export default styled(Home)`


`