import Head from "next/head";
import styled from "styled-components";
import Contact from "../sections/Contact";
import CourseList from "../sections/CourseList";
import Hero from "../sections/Hero";
import PostList from "../sections/PostList";
import Questions from "../sections/Questions";
import fetch from 'isomorphic-unfetch'
import endpoints from "../services/api";



export const getServerSideProps = async ()=>{
  const response = await fetch(endpoints.posts.post_list)
  const data = await response.json()
  return {
    props:{
      postData : data
    }
  }
}



function Home({ className, postData }) {
 

  return (
    <>
      <Head>
        <title>BIMCapacitacion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Questions />
      <CourseList />
      <PostList postData={postData}/>
      <Contact displayImage={true}/>
    </>
  );
}

export default styled(Home)``;
