import Head from "next/head";
import styled from "styled-components";
import Contact from "../sections/Contact";
import CourseList from "../sections/CourseList";
import Hero from "../sections/Hero";
import PostList from "../sections/PostList";
import Questions from "../sections/Questions";
import { useFetch } from "../hooks/useFetch"; 
import   { leContext } from "../hooks/useContext";
import endpoints from "../services/api";


function Home({ className }) {
  const context = leContext()
  const postData = useFetch(endpoints.posts.post_list)
  context.setPostList(postData)
  // console.log('Navbar',postData);
 

  return (
    <>
      <Head>
        <title>BIMCapacitacion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Questions />
      <CourseList />
      <PostList />
      <Contact />
    </>
  );
}

export default styled(Home)``;
